package testdata

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"restrail/internal/openapi"
	"strings"
)

// VersionFields lists field names that represent optimistic locking versions.
// These are excluded from random generation and should be carried forward
// from prior API responses instead.
var VersionFields = []string{"version", "v", "ver"}

// isServerGeneratedID reports whether a field name looks like a primary key
// that is typically auto-generated by the server (e.g., "id", "Id", "ID", "_id").
func isServerGeneratedID(name string) bool {
	switch name {
	case "id", "Id", "ID", "_id":
		return true
	}
	return false
}

// IsVersionField reports whether a field name matches a known version field (case-insensitive).
func IsVersionField(name string) bool {
	lower := strings.ToLower(name)
	for _, vf := range VersionFields {
		if lower == vf {
			return true
		}
	}
	return false
}

// Factory generates test data from an OpenAPI schema.
type Factory interface {
	Generate(schema *openapi.Schema) (map[string]interface{}, error)
}

// RandomFactory generates random test data with a fixed seed for reproducibility.
type RandomFactory struct {
	rng               *rand.Rand
	OptimisticLocking bool
}

// NewRandomFactory creates a factory with a fixed seed for deterministic output.
func NewRandomFactory(optimisticLocking bool) *RandomFactory {
	return &RandomFactory{
		rng:               rand.New(rand.NewSource(42)),
		OptimisticLocking: optimisticLocking,
	}
}

func (f *RandomFactory) Generate(schema *openapi.Schema) (map[string]interface{}, error) {
	if schema == nil {
		return map[string]interface{}{}, nil
	}
	val := f.generateValue(schema)
	if m, ok := val.(map[string]interface{}); ok {
		return m, nil
	}
	return map[string]interface{}{"value": val}, nil
}

func (f *RandomFactory) generateValue(schema *openapi.Schema) interface{} {
	if schema == nil {
		return nil
	}

	// Handle allOf by merging
	if len(schema.AllOf) > 0 {
		merged := make(map[string]interface{})
		for _, sub := range schema.AllOf {
			val := f.generateValue(sub)
			if m, ok := val.(map[string]interface{}); ok {
				for k, v := range m {
					merged[k] = v
				}
			}
		}
		return merged
	}

	// Handle oneOf/anyOf by picking first
	if len(schema.OneOf) > 0 {
		return f.generateValue(schema.OneOf[0])
	}
	if len(schema.AnyOf) > 0 {
		return f.generateValue(schema.AnyOf[0])
	}

	// Handle enum
	if len(schema.Enum) > 0 {
		idx := f.rng.Intn(len(schema.Enum))
		var val interface{}
		json.Unmarshal(schema.Enum[idx], &val)
		return val
	}

	switch schema.Type {
	case "object":
		return f.generateObject(schema)
	case "array":
		return f.generateArray(schema)
	case "string":
		return f.generateString(schema)
	case "integer":
		return f.generateInteger(schema)
	case "number":
		return f.generateNumber(schema)
	case "boolean":
		return f.rng.Intn(2) == 1
	default:
		// If type is empty but has properties, treat as object
		if len(schema.Properties) > 0 {
			return f.generateObject(schema)
		}
		return "test_value"
	}
}

func (f *RandomFactory) generateObject(schema *openapi.Schema) map[string]interface{} {
	result := make(map[string]interface{})
	required := make(map[string]bool)
	for _, r := range schema.Required {
		required[r] = true
	}
	for name, prop := range schema.Properties {
		if prop.ReadOnly {
			continue
		}
		// Skip version fields — these must come from prior API responses
		if f.OptimisticLocking && IsVersionField(name) {
			continue
		}
		// Skip non-required ID fields — these are typically server-generated
		// (e.g., when the response schema is reused as the POST body schema)
		if !required[name] && isServerGeneratedID(name) {
			continue
		}
		// Always generate required fields; 50% chance for optional
		if required[name] || f.rng.Intn(2) == 1 {
			result[name] = f.generateValue(prop)
		}
	}
	return result
}

func (f *RandomFactory) generateArray(schema *openapi.Schema) []interface{} {
	count := 1 + f.rng.Intn(3) // 1-3 items
	var items []interface{}
	for i := 0; i < count; i++ {
		items = append(items, f.generateValue(schema.Items))
	}
	return items
}

func (f *RandomFactory) generateString(schema *openapi.Schema) string {
	switch schema.Format {
	case "email":
		return fmt.Sprintf("test_%s@example.com", f.randomAlphaNum(6))
	case "date":
		return "2024-01-15"
	case "date-time":
		return "2024-01-15T10:30:00Z"
	case "uuid":
		return f.randomUUID()
	case "uri", "url":
		return fmt.Sprintf("https://example.com/%s", f.randomAlphaNum(6))
	}

	length := 8
	if schema.MinLength != nil && *schema.MinLength > length {
		length = *schema.MinLength
	}
	if schema.MaxLength != nil && *schema.MaxLength < length {
		length = *schema.MaxLength
	}
	return "test_" + f.randomAlphaNum(length)
}

func (f *RandomFactory) generateInteger(schema *openapi.Schema) int {
	min := 1
	max := 1000
	if schema.Minimum != nil {
		min = int(*schema.Minimum)
	}
	if schema.Maximum != nil {
		max = int(*schema.Maximum)
	}
	if max <= min {
		return min
	}
	return min + f.rng.Intn(max-min+1)
}

func (f *RandomFactory) generateNumber(schema *openapi.Schema) float64 {
	min := 0.0
	max := 1000.0
	if schema.Minimum != nil {
		min = *schema.Minimum
	}
	if schema.Maximum != nil {
		max = *schema.Maximum
	}
	return min + f.rng.Float64()*(max-min)
}

func (f *RandomFactory) randomAlphaNum(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	var b strings.Builder
	for i := 0; i < n; i++ {
		b.WriteByte(chars[f.rng.Intn(len(chars))])
	}
	return b.String()
}

func (f *RandomFactory) randomUUID() string {
	var uuid [16]byte
	for i := range uuid {
		uuid[i] = byte(f.rng.Intn(256))
	}
	uuid[6] = (uuid[6] & 0x0f) | 0x40 // version 4
	uuid[8] = (uuid[8] & 0x3f) | 0x80 // variant 1
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		uuid[0:4], uuid[4:6], uuid[6:8], uuid[8:10], uuid[10:16])
}
