package plan

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Step represents a single step in the execution plan.
type Step struct {
	Filename    string
	Annotations []string // e.g., "EXTRACT_ID", "INJECT_FK field=source_domain"
}

// ExecutionPlan represents a parsed execution.plan file.
type ExecutionPlan struct {
	Profile       string
	Domains       []string
	Dependencies  []string          // raw dependency metadata lines
	ParamMappings map[string]string // paramName -> domain ("$" = current domain)
	Phases        []Phase
}

// Phase groups steps under a phase header.
type Phase struct {
	Name  string
	Steps []Step
}

// AllSteps returns all steps across all phases in order.
func (p *ExecutionPlan) AllSteps() []Step {
	var steps []Step
	for _, phase := range p.Phases {
		steps = append(steps, phase.Steps...)
	}
	return steps
}

// HasAnnotation checks if a step has a specific annotation.
func (s Step) HasAnnotation(prefix string) bool {
	for _, a := range s.Annotations {
		if strings.HasPrefix(a, prefix) {
			return true
		}
	}
	return false
}

// GetAnnotationValue returns the value part of an annotation like "INJECT_FK field=source".
func (s Step) GetAnnotationValue(prefix string) string {
	for _, a := range s.Annotations {
		if strings.HasPrefix(a, prefix) {
			rest := strings.TrimPrefix(a, prefix)
			return strings.TrimSpace(rest)
		}
	}
	return ""
}

// Write writes the execution.plan file to disk.
func Write(dir string, profileName string, phases []Phase, domains []string, depLines []string, paramMappings map[string]string) error {
	var b strings.Builder

	fmt.Fprintln(&b, "# Execution Plan")
	fmt.Fprintln(&b, "# Generated by restrail init")
	fmt.Fprintf(&b, "# Profile: %s\n", profileName)
	fmt.Fprintf(&b, "# Domains: %d\n", len(domains))
	fmt.Fprintln(&b)

	// Metadata
	fmt.Fprintf(&b, "# @profile %s\n", profileName)
	fmt.Fprintf(&b, "# @domains %s\n", strings.Join(domains, ","))
	for _, dep := range depLines {
		fmt.Fprintf(&b, "# @dependency %s\n", dep)
	}
	if len(paramMappings) > 0 {
		// Sort keys for deterministic output
		keys := make([]string, 0, len(paramMappings))
		for k := range paramMappings {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "# @param_mapping %s=%s\n", k, paramMappings[k])
		}
	}
	fmt.Fprintln(&b)

	for _, phase := range phases {
		fmt.Fprintf(&b, "# %s\n", phase.Name)
		for _, step := range phase.Steps {
			line := step.Filename
			for _, ann := range step.Annotations {
				line += " -> " + ann
			}
			fmt.Fprintln(&b, line)
		}
		fmt.Fprintln(&b)
	}

	return os.WriteFile(dir+"/execution.plan", []byte(b.String()), 0644)
}

// Parse reads an execution.plan file and returns the structured plan.
func Parse(path string) (*ExecutionPlan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading plan file: %w", err)
	}
	return ParseContent(string(data))
}

// ParseContent parses the text content of an execution.plan.
func ParseContent(content string) (*ExecutionPlan, error) {
	p := &ExecutionPlan{}
	scanner := bufio.NewScanner(strings.NewReader(content))

	var currentPhase *Phase

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "" {
			continue
		}

		// Metadata comments
		if strings.HasPrefix(line, "# @profile ") {
			p.Profile = strings.TrimPrefix(line, "# @profile ")
			continue
		}
		if strings.HasPrefix(line, "# @domains ") {
			p.Domains = strings.Split(strings.TrimPrefix(line, "# @domains "), ",")
			continue
		}
		if strings.HasPrefix(line, "# @dependency ") {
			p.Dependencies = append(p.Dependencies, strings.TrimPrefix(line, "# @dependency "))
			continue
		}
		if strings.HasPrefix(line, "# @param_mapping ") {
			raw := strings.TrimPrefix(line, "# @param_mapping ")
			parts := strings.SplitN(raw, "=", 2)
			if len(parts) == 2 {
				if p.ParamMappings == nil {
					p.ParamMappings = make(map[string]string)
				}
				p.ParamMappings[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
			continue
		}

		// Phase header (non-metadata comment lines)
		if strings.HasPrefix(line, "# Phase") || (strings.HasPrefix(line, "#") &&
			!strings.HasPrefix(line, "# @") &&
			!strings.HasPrefix(line, "# Execution") &&
			!strings.HasPrefix(line, "# Generated") &&
			!strings.HasPrefix(line, "# Profile") &&
			!strings.HasPrefix(line, "# Domains")) {
			name := strings.TrimPrefix(line, "# ")
			p.Phases = append(p.Phases, Phase{Name: name})
			currentPhase = &p.Phases[len(p.Phases)-1]
			continue
		}

		// Skip other comments
		if strings.HasPrefix(line, "#") {
			continue
		}

		// Step line
		step := Step{}
		if idx := strings.Index(line, " -> "); idx != -1 {
			step.Filename = line[:idx]
			annParts := strings.Split(line[idx+4:], " -> ")
			for _, a := range annParts {
				step.Annotations = append(step.Annotations, strings.TrimSpace(a))
			}
		} else {
			step.Filename = line
		}

		if currentPhase == nil {
			p.Phases = append(p.Phases, Phase{Name: "default"})
			currentPhase = &p.Phases[len(p.Phases)-1]
		}
		currentPhase.Steps = append(currentPhase.Steps, step)
	}

	return p, nil
}
